[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "FlorianeJN", email = "Floriane.nikebie.1@etsmtl.net" }
]
requires-python = ">=3.11"
dependencies = [
    "deepagents>=0.7.12",
    "fastapi>=0.141.1",
    "langchain-google-genai>=4.4.0",
    "langgraph>=1.2.11",
    "uvicorn>=0.52.4",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
